import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Scanner;

public class InputAnalyzer {

    private Scanner scanner = new Scanner(System.in);
    private List<Integer> inputs = new ArrayList<>();

    /**
     * @return list of five users inputs
     */

    public List<Integer> userInput() {
        System.out.println("Input five numbers:");
        int i = 0;
        do {
            inputs.add(scanner.nextInt());
            i++;
        } while (i < 5);
        return inputs;
    }

    /**
     * Compares two lists of numbers.
     * @param inputted list of five numbers inputted by the user.
     * @param generated list of five numbers randomly generated by the machine.
     * @return a list of numbers that match machine-generated numbers
     */

    public List<Integer> numbersAreEqualCheck(List<Integer> inputted, List<Integer> generated) {
        for (int i = 0; i < inputted.size(); i++) {
            if (!generated.contains(inputted.get(i))) {
                inputted.remove(i);
                i--;
            }
        }
        for (int i = 0; i < generated.size(); i++) {
            if (inputted.contains(generated.get(i))) {
                generated.remove(i);
                i--;
            }
        }
        return inputted;
    }
}
